[ASL] Rework binary operation effects on symbolic constraints
herd/herdtools7 pull request #1008
Opened 2024-10-15 13:41 UTC by HadrienRenaud

- [x] Reorganise the code for binary-operation checking: it is now more explicit and shorter.
- [x] Improve DIV results by considering it decreasing on its second argument (see bug report later)
- [x] Add test for this
- [x] Merge static intervals after divisions using a diet
- [x] Implement `constraint_binop` for `MOD` and remove all usages of this strange default to `UnConstrained`
- [x] Fix DIV implementation: DIV is not decreasing for negative numerators.
- [x] Fix MUL, SHR, SHL, POW implementation: they are not increasing if one operand is negative.

---

### Bug report

With the following test, we can see that the results of divisions on constraints are defaulting to the unconstrained integer. This is unwanted behaviour.

```
func main() =>integer
begin
  let a : integer {10} = 10;
  let b : integer {10..20} = 10;
  var c = b DIV a;
  var d = a DIV b;
  c = 1.0; // will error so that the type is printed
  d = 1.0; // will error so that the type is printed
  return 0;
end
```

Previous output for this test:
```
❯ aslref tests-asl/1008.asl --type-check-warn
File tests-asl/1008.asl, line 7, characters 2 to 3:
ASL Typing error: a subtype of integer {1..2} was expected, provided real.
File tests-asl/1008.asl, line 8, characters 2 to 3:
ASL Typing error: a subtype of integer was expected, provided real.
```

Current output for this test:
```
❯ dune exec aslref -- tests-asl/1008.asl --type-check-warn
File tests-asl/1008.asl, line 7, characters 2 to 3:
ASL Typing error: a subtype of integer {1..2} was expected, provided real.
File tests-asl/1008.asl, line 8, characters 2 to 3:
ASL Typing error: a subtype of integer {1} was expected, provided real.
```

2024-10-16 08:58 UTC, maranget commented
Hi @HadrienRenaud, I am not sure that the warnings are always useful : "trop de warning tue le warning". Maybe we should consider various levels of verbosity controlled by some command-line option?

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +
(**
Tests whether the value of binary operation [op] increases along with its left-hand-side operand when all operands are non-negative. That is, if [is_left_increasing op] is true then for every two expressions [x1 op y] and [x2 op y] such that [x1 >= 0 /\ x2 >= 0 /\ y >=0] and [x1 <= x2] then [x1 op y <= x2 op y].
*)

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +  | MUL | SHL | SHR | POW | PLUS | MINUS -> true
If you agree with the definition given by my comment above, shouldn't DIV/DIVRM be true?

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +  | DIV | DIVRM | AND | BAND | BEQ | MOD | BOR | EOR | EQ_OP | GT | GEQ | IMPL
Shouldn't the result for MOD be false, rather than a failed assertion?
It looks like the function either returns true or fails.

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
>  let is_right_increasing = function
(**
Tests whether the value of binary operation [op] increases along with its right-hand-side operand when all operands are non-negative. That is, if [is_right_increasing op] is true then for every two expressions [x op y1] and [x op y2] such that [y1 >= 0 /\ y2 >= 0 /\ x >=0]  and [y1 <= y2] then [x op y1 <= x op y2].
*)

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +  | MINUS -> false
shouldn't SHR be false? 8 >> 1 is greater than 8 >> 2

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/Typing.ml
> +    | DIV | DIVRM -> (* general case loses too much precision *) true
I don't understand the comment. Perhaps add a comment explaining this function?

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
>  let is_right_decreasing = function
(**
Tests whether the value of binary operation [op] decreases along with its right-hand-side operand when all operands are non-negative. That is, if [is_right_decreasing op] is true then for every two expressions [x op y1] and [x op y2] such that [y1 >= 0 /\ y2 >= 0 /\ x >=0] and [y1 <= y2] then [x op y1 <= x op y2].
*)

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
>  let is_right_decreasing = function
Do we even need this function? It's the boolean negation of is_right_incvreasing.

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +    | Constraint_Exact e1, Constraint_Range (_e21, e22) ->
Is this correct?
For example `10 DIV 1..10` = `1, 2, 5, 10`, not `[10..1, 1..10]`

2024-10-17 16:43 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +    | Constraint_Range (e11, e12), Constraint_Range (_e21, _e22) ->
Likewise, I'm not sure the result is a fixed number of ranges.

2024-10-23 19:27 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +let list_take =
How about renaming to list_prefix?

2024-10-24 15:38 UTC, Roman-Manevich commented on asllib/ASTUtils.ml
> +let list_take =
Okay, but how about a documentation comment saying that it returns a prefix?

2024-10-28 13:02 UTC, Roman-Manevich requested changes

2024-10-28 13:02 UTC, Roman-Manevich commented on asllib/StaticOperations.ml
> +(* Begin FilterReduceConstraintDiv *)
It's getting hard to follow the logic here. I think some comments could help.

2024-11-06 18:14 UTC, merged