Segmenting large configuration files
herd/herdtools7 pull request #348
Opened 2022-03-15 09:53 UTC by hugookeeffe

The purpose of this script is to segment a large configuration file and run it with diy7. This was made in order to be able to generate more tests for certain configuration files and to reduce run time for certain large configuration files.

2022-03-16 11:38 UTC, maranget commented
Hi @hugookeeffe, the script is useful, thanks. I ran it and notice the following problems:

- Some lines in the @all file us ends with the two characters `\` \n` (_i.e._ backslash followed by n). This prevents the file from being used by other tools. I tried `name7 @all`.
- May I suggest another organisation of tests: create sub-directories src00, src01 etc. with each directory containing its `.conf` files, the tests and its `@all` file; and a toplevel `@all` files that simply lists `src00/@all`, `src01/@all` etc.

2022-03-18 15:21 UTC, hugookeeffe commented
> Hi @hugookeeffe, the script is useful, thanks. I ran it and notice the following problems:
> 
> * Some lines in the `@all` file us ends with the two characters `\`  and `n` (_i.e._ backslash followed by n). This prevents the file from being used by other tools. I tried `name7 @all`.
I think I have solved this issue in the newest commit, let me know if it still does not work.
> * May I suggest another organisation of tests: create sub-directories src00, src01 etc. with each directory containing its `.conf` files, the tests and its `@all` file; and a toplevel `@all` files that simply lists `src00/@all`, `src01/@all` etc.
I have implemented this change in the newest commit

Let me know if there are any other changes you would like me to make

2022-03-25 14:27 UTC, maranget requested changes
Some leftover `\` `n` sequence still here, trying  github commit.

2022-03-25 14:27 UTC, maranget commented on tools/segment.sh
> +    echo "\n" >>@all
This lines introduces untimely `\` `n` sequences in the output file `@all`. Deleting it apparently solves the problem: 
```suggestion
```

2022-03-25 14:33 UTC, merged

2022-03-25 14:33 UTC, maranget commented
Merged, thanks